export const DATA = [
  {
    createdAt: 1732005816,
    title: "Global Tech Giants Invest in AI Research",
    description: "Major companies are pouring resources into AI development.",
    text: "Tech companies like Google, Microsoft, and Apple are increasing investments in artificial intelligence research. Experts say these advancements could revolutionize industries from healthcare to transportation. However, ethical concerns remain about the rapid growth of AI technologies. Governments are also exploring regulations to address these challenges.",
    createdBy: "Tech Daily",
    id: "1",
  },
  {
    createdAt: 1732005756,
    title: "Record-Breaking Storm Hits Southeast Asia",
    description:
      "Typhoon Clara causes widespread devastation across the region.",
    text: "Southeast Asia is reeling from the impact of Typhoon Clara, which has been described as one of the most powerful storms in decades. Thousands have been displaced, with rescue operations underway to assist affected communities. Meteorologists warn that climate change may be contributing to the increased frequency and intensity of such storms. Relief efforts are being coordinated by international organizations.",
    createdBy: "World News Network",
    id: "2",
  },
  {
    createdAt: 1732005696,
    title: "Scientists Discover Water on Mars",
    description:
      "NASA confirms the presence of liquid water beneath the Martian surface.",
    text: "In a groundbreaking discovery, NASA has confirmed the existence of liquid water on Mars, located in underground reservoirs. This finding boosts hopes for potential microbial life and future human colonization. Researchers are now planning additional missions to explore these water sources further. The discovery has reignited public interest in space exploration.",
    createdBy: "Science Today",
    id: "3",
  },
  {
    createdAt: 1732005636,
    title: "Electric Cars Gain Popularity Worldwide",
    description: "Sales of electric vehicles see a record surge in 2024.",
    text: "Electric vehicles (EVs) are becoming increasingly popular, with global sales reaching unprecedented levels this year. Major manufacturers are ramping up production to meet demand as governments introduce incentives for green energy solutions. Despite this progress, challenges such as charging infrastructure and battery production remain. Analysts predict EVs will dominate the auto market within the next decade.",
    createdBy: "Green Energy News",
    id: "4",
  },
  {
    createdAt: 1732005576,
    title: "Breakthrough in Cancer Research Offers Hope",
    description: "New therapy shows promise in early clinical trials.",
    text: "Researchers have developed a novel cancer treatment that uses modified immune cells to target tumors. Early trials have shown remarkable success in reducing cancer progression in patients. While the therapy is still in its experimental stages, it has been hailed as a significant step forward in oncology. Experts caution that further testing is needed before it can be widely adopted.",
    createdBy: "Health Weekly",
    id: "5",
  },
  {
    createdAt: 1732005516,
    title: "Global Markets Rally Amid Economic Optimism",
    description: "Stock markets surge as investors regain confidence.",
    text: "Global financial markets have seen a significant upswing, with major indices reporting record highs. Investors are optimistic about economic recovery following better-than-expected earnings reports from leading companies. Economists attribute the rally to improving consumer confidence and declining inflation rates. However, some caution that geopolitical tensions could still impact future performance.",
    createdBy: "Finance Today",
    id: "6",
  },
  {
    createdAt: 1732005456,
    title: "Historic Agreement Reached at Climate Summit",
    description: "World leaders commit to bold climate action.",
    text: "At this year’s Climate Summit, global leaders signed an agreement to reduce carbon emissions by 50% over the next decade. The pact has been described as a historic milestone in the fight against climate change. Environmental groups have praised the commitment but stress that implementation will be key. Critics remain skeptical about enforcement mechanisms.",
    createdBy: "Eco News",
    id: "7",
  },
  {
    createdAt: 1732005396,
    title: "Breakthrough Technology Enables Wireless Power",
    description: "New innovation could revolutionize energy delivery.",
    text: "A startup has unveiled a breakthrough technology that allows electricity to be transmitted wirelessly over long distances. This innovation could eliminate the need for traditional power lines and transform energy access in remote areas. Industry experts are calling this a potential game-changer for renewable energy integration. However, questions about safety and scalability remain.",
    createdBy: "Innovation Weekly",
    id: "8",
  },
  {
    createdAt: 1732005336,
    title: "Archaeologists Unearth Ancient City in Egypt",
    description: "Stunning discovery sheds light on ancient civilizations.",
    text: "Archaeologists in Egypt have uncovered the remains of a 4,000-year-old city believed to have been a major trade hub. The site includes well-preserved structures, pottery, and artifacts that provide insights into daily life during the era. Historians are calling it one of the most significant discoveries of the decade. Excavations are ongoing to reveal more details.",
    createdBy: "History Monthly",
    id: "9",
  },
  {
    createdAt: 1732005276,
    title: "Olympics to Feature New Sports in 2028",
    description: "Exciting additions announced for the Los Angeles Games.",
    text: "The International Olympic Committee has announced that cricket, flag football, and squash will debut at the 2028 Summer Games in Los Angeles. The decision aims to attract a younger and more diverse audience to the Olympics. Athletes and fans worldwide have welcomed the news with enthusiasm. Preparations are underway to integrate these sports into the competition schedule.",
    createdBy: "Sports Insider",
    id: "10",
  },
  {
    createdAt: 1732014907993,
    title: "Dolazak",
    description: "Da li ce Sredo doci danas? ",
    text: "Mozda da, mozda ne!?\nAli verovatno ne!",
    createdBy: "Sredo",
    id: "11",
  },
];
